apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-python-app-pv
  namespace: t002-u000001
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/root/hrushi/lib"
    type: DirectoryOrCreate