apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-python-app-pvc
  namespace: t002-u000001
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual